export const fslPhrases = [
  {
    id: 1,
    phrase: "Hello",
    filipino: "Kumusta",
    category: "Greetings",
    description: "A basic greeting used when meeting someone.",
    keywords: ["hello", "hi", "kumusta"],
    video: null,
  },
  {
    id: 2,
    phrase: "Good morning",
    filipino: "Magandang umaga",
    category: "Greetings",
    description: "A greeting commonly used in the morning.",
    keywords: ["good morning", "magandang umaga"],
    video: null,
  },
  {
    id: 3,
    phrase: "Good afternoon",
    filipino: "Magandang hapon",
    category: "Greetings",
    description: "A greeting commonly used in the afternoon.",
    keywords: ["good afternoon", "magandang hapon"],
    video: null,
  },
  {
    id: 4,
    phrase: "Good evening",
    filipino: "Magandang gabi",
    category: "Greetings",
    description: "A greeting commonly used in the evening.",
    keywords: ["good evening", "magandang gabi"],
    video: null,
  },
  {
    id: 5,
    phrase: "Thank you",
    filipino: "Salamat",
    category: "Common Phrases",
    description: "Used to express gratitude.",
    keywords: ["thank you", "thanks", "salamat"],
    video: null,
  },
  {
    id: 6,
    phrase: "Please",
    filipino: "Pakiusap",
    category: "Common Phrases",
    description: "Used when politely requesting something.",
    keywords: ["please", "pakiusap"],
    video: null,
  },
  {
    id: 7,
    phrase: "Please repeat",
    filipino: "Pakiulit",
    category: "Classroom",
    description: "Used when asking someone to repeat what they said.",
    keywords: [
      "please repeat",
      "repeat please",
      "repeat that",
      "say that again",
      "can you repeat",
      "pakiulit",
    ],
    video: null,
  },
  {
    id: 8,
    phrase: "I don't understand",
    filipino: "Hindi ko maintindihan",
    category: "Classroom",
    description: "Used when the speaker's message is unclear.",
    keywords: [
      "i don't understand",
      "i dont understand",
      "do not understand",
      "don't understand",
      "dont understand",
      "hindi ko maintindihan",
    ],
    video: null,
  },
  {
    id: 9,
    phrase: "Yes",
    filipino: "Oo",
    category: "Common Phrases",
    description: "Used to indicate agreement or confirmation.",
    keywords: ["yes", "yeah", "oo"],
    video: null,
  },
  {
    id: 10,
    phrase: "No",
    filipino: "Hindi",
    category: "Common Phrases",
    description: "Used to indicate disagreement or refusal.",
    keywords: ["no", "nope", "hindi"],
    video: null,
  },
  {
    id: 11,
    phrase: "Help",
    filipino: "Tulong",
    category: "Emergency",
    description: "Used when assistance is needed.",
    keywords: ["help", "help me", "tulong", "tulungan"],
    video: null,
  },
  {
    id: 12,
    phrase: "Are you okay?",
    filipino: "Okay ka lang ba?",
    category: "Emergency",
    description: "Used to check if another person is safe or well.",
    keywords: [
      "are you okay",
      "are you alright",
      "you okay",
      "okay ka lang ba",
    ],
    video: null,
  },
];